<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>troubleshooting on 로코</title>
    <link>https://nmin11.github.io/kr/tags/troubleshooting/</link>
    <description>Recent content in troubleshooting on 로코</description>
    <generator>Hugo -- gohugo.io</generator>
    <lastBuildDate>Sat, 01 Jul 2023 00:00:00 +0000</lastBuildDate><atom:link href="https://nmin11.github.io/kr/tags/troubleshooting/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>의문의 S3 Access Denied 에러</title>
      <link>https://nmin11.github.io/kr/blog/s3-access-denied-error/</link>
      <pubDate>Sat, 01 Jul 2023 00:00:00 +0000</pubDate>
      
      <guid>https://nmin11.github.io/kr/blog/s3-access-denied-error/</guid>
      <description>에러를 발견하게 된 계기 사실은 똑같은 에러를 두 번이나 겪었다.
두 번 다 회사 업무 중 발생한 에러는 아니었지만, 둘 다 회사 업무와 관련된 기능을 테스트해 보기 위해서 구현했던 사이드에서 발생했다.
구현했던 것은 S3에 객체가 생성되었을 때, 그 event로 트리거되는 Lambda 함수였다.
해당 Lambda 함수들은 공통적으로 받은 event로부터 객체의 key name을 가져오고, 해당 key name을 통해 객체 정보를 다시 조회하는 로직이었다.
하지만 내 Lambda 함수들은 알 수 없는 Access Denied 에러를 반환했다.</description>
    </item>
    
  </channel>
</rss>
